In [10]:
from sqlalchemy.engine import create_engine
import pandas as pd
import numpy as np
import json
import gzip
import cx_Oracle
from datetime import datetime, timedelta, date
import calendar

In [11]:
DIALECT = 'oracle'
SQL_DRIVER = 'cx_oracle'
USERNAME = 'DEV' #enter your username
PASSWORD = "qtdata@2021" #enter your password
HOST = '118.69.32.128' #enter the oracle db host url
PORT = 1521 #enter the oracle port number
SERVICE = 'XE' #enter the oracle db service name
ENGINE_PATH_WIN_AUTH = DIALECT + '+' + SQL_DRIVER + '://' + USERNAME + ':' + PASSWORD +'@' + HOST + \
                       ':' + str(PORT) + '/'+ SERVICE + '?encoding=UTF-8&nencoding=UTF-8'
print(ENGINE_PATH_WIN_AUTH)
engine = create_engine(ENGINE_PATH_WIN_AUTH, max_identifier_length = 128)
con = engine.connect()

oracle+cx_oracle://DEV:qtdata@2021@118.69.32.128:1521/XE?encoding=UTF-8&nencoding=UTF-8

In [94]:
db_temponote = 'qt_temponote'
db_tempomonitor = 'qt_tempomonitor'
db_memberinfo = 'qt_memberinfo'
db_weeklyreport = 'qt_weeklyreport'
db_functions = 'qt_functions'
db_transport = 'qt_transport'
db_product_expansion_plan = 'qt_product_expansion_plan'

username = "PHUNG THANH AN"

df = pd.read_sql("select * from {} WHERE NAME like '{}' AND \
                 DATETIME = (select max(DATETIME) from {} where NAME like '{}')"\
    .format(db_tempomonitor, username, db_tempomonitor, username), engine)

# df = pd.read_sql("\
#                   (select * from {} \
#                   where NAME like '{}' AND datetime LIKE to_char(max(datetime),'DD-MON-YY')\
#                   "\
#     .format(db_tempomonitor, db_tempomonitor, username), engine)
# df = pd.read_sql("select * from {}"\
#     .format(db_tempomonitor, username), engine)
print(df)

             datetime            name  \
0 2020-07-10 17:20:55  PHUNG THANH AN

                                              screen      time  \
0  iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  17:20:55

                                              webcam
0  iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...

In [24]:
df = pd.read_sql("select * from {} where NAME like '{}'\
                  "\
    .format(db_tempomonitor, username), engine)
df.columns = [x.upper() for x in df.columns]

screen_b64 = df.iloc[-1]['SCREEN']
print(df)
print(time)

              DATETIME            NAME  \
0  2020-07-09 22:53:37  PHUNG THANH AN
1  2020-07-09 22:54:07  PHUNG THANH AN
2  2020-07-09 22:54:37  PHUNG THANH AN
3  2020-07-09 22:55:07  PHUNG THANH AN
4  2020-07-09 22:55:37  PHUNG THANH AN
5  2020-07-09 22:56:07  PHUNG THANH AN
6  2020-07-09 22:56:37  PHUNG THANH AN
7  2020-07-09 22:45:39  PHUNG THANH AN
8  2020-07-09 22:46:09  PHUNG THANH AN
9  2020-07-09 22:46:39  PHUNG THANH AN
10 2020-07-09 22:47:09  PHUNG THANH AN
11 2020-07-09 22:47:39  PHUNG THANH AN
12 2020-07-09 22:48:09  PHUNG THANH AN

                                               SCREEN      TIME  \
0   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:53:37
1   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:54:07
2   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:54:37
3   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:55:07
4   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:55:37
5   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:56:07
6   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:56:37
7   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:45:39
8   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:46:09
9   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:46:39
10  iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:47:09
11  iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:47:39
12  iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...  22:48:09

                                               WEBCAM
0   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
1   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
2   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
3   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
4   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
5   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
6   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
7   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
8   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
9   iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
10  iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
11  iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...
12  iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAA...

NameError: name 'time' is not defined

In [20]:
db_functions = 'qt_tempomonitor'
df = pd.read_sql("select to_char(name) as name, max(datetime) as date_modified from {} GROUP BY to_char(name)".format(db_functions), engine)
print(df[:])

              name date_modified
0          CRIS VO    2020-07-09
1  TRAN TRUNG MINH    2020-07-09
2   PHUNG THANH AN    2020-07-09

In [ ]:
db_memberinfo = 'QT_MEMBERINFO'
df_report = pd.read_excel('qt_memberinfo.xlsx')
df_report.columns = [x.upper() for x in df_report.columns]
df_report['DATE_MODIFIED'] = datetime.now()
col_name = df_report.dtypes.index
log = ''
try:
    for col in col_name:
        #convert to datetime
        if col == 'TIMESTAMP'or col == 'STARTDATE' or col == 'OUTDATE' or col == 'DATE_MODIFIED':
            if df_report[col].dtypes == 'float':
                df_report[col] = pd.to_datetime(df_report[col], format='%m%d%Y', errors='coerce')
            if df_report[col].dtypes != 'datetime64[ns]':
                log += 'Upload failed, fill correct the type of {} column is m/dd/yyyy\n'.format(col)
        else:
            #convert to string
            df_report[col] = df_report[col].astype(str)
    
    if log == '':
        #Insert changed rows
        df_report.to_sql(db_memberinfo, engine, if_exists = 'append', index = False)
        log += 'Upload successful'
    print(log)
    
except:
    print('Upload failed')

In [ ]:
db_memberinfo = 'QT_MEMBERINFO'
df_report = pd.read_excel('qt_memberinfo.xlsx')
df_report.columns = [x.upper() for x in df_report.columns]
df_report['DATE_MODIFIED'] = datetime.now()
col_name = df_report.dtypes.index
log = ''
try:
    for col in col_name:
        #convert to datetime
        if col == 'TIMESTAMP'or col == 'STARTDATE' or col == 'OUTDATE' or col == 'DATE_MODIFIED':
            if df_report[col].dtypes == 'float':
                df_report[col] = pd.to_datetime(df_report[col], format='%m%d%Y', errors='coerce')
            if df_report[col].dtypes != 'datetime64[ns]':
                log += 'Upload failed, fill correct the type of {} column is m/dd/yyyy\n'.format(col)
        else:
            #convert to string
            df_report[col] = df_report[col].astype(str)
    
    if log == '':
        #Insert changed rows
        #df_report.to_sql(db_memberinfo, engine, if_exists = 'append', index = False)
        log += 'Upload successful'
    print(log)
    
except:
    print('Upload failed')

In [15]:
db_functions = 'QT_MEMBERINFO'
df = pd.read_sql("select * from {}".format(db_functions), engine)
print(df)

DatabaseError: (cx_Oracle.DatabaseError) ORA-00942: table or view does not exist
[SQL: select * from QT_MEMBERINFO]
(Background on this error at: http://sqlalche.me/e/4xp6)

In [3]:
db_functions = 'qt_functions'
df = pd.read_sql("select * from {} where LIB not like 'sys_file'".format(db_functions), engine)
print(df)

                    function  \
0             push_transport
1              get_transport
2   push_recruitment_longhai
3     push_recruitment_group
4      get_recruitment_group
5             get_memberinfo
6        run_hubspot_message
7         send_facebookgroup
8     run_facebook_grouppost
9           check_permission
10                     hello
11                        hi
12          get_weeklyreport
13         push_weeklyreport
14                 push_note
15              get_filepath
16            get_folderpath
17             list_function
18             push_function
19              get_function
20              push_sysfile
21   get_recruitment_longhai
22      push_recruitment_hr2
23       get_recruitment_hr2
24               get_sysfile
25                    whatis
26             check_version
27                    backup
28                  rollback
29     check_exists_by_class
30            custom_subject
31            custom_message
32             send_facebook
33      run_facebook_message
34             send_linkedin
35      run_linkedin_message
36              send_hubspot
37                send_gmail
38         run_gmail_message
39    push_product_expansion
40     get_product_expansion

                                              content             lib  \
0   def push_transport():\n    import pandas as pd...      lib_custom
1   def get_transport(status='all'):\n    import p...      lib_custom
2   def push_recruitment_longhai():\n    import pa...      lib_custom
3   def push_recruitment_group():\n    import pand...      lib_custom
4   def get_recruitment_group(status='all'):\n    ...      lib_custom
5   import pandas as pd\nfrom datetime import date...  lib_memberinfo
6   def run_hubspot_message(min_delay = 3):\n    l...         lib_bot
7   def send_facebookgroup(browser, facebook_group...         lib_bot
8   def run_facebook_grouppost(min_delay = 3):\n  ...         lib_bot
9   def check_permission():\n    from datetime imp...      lib_custom
10  def hello(text = 'Hello, world!'):\n    return...      lib_custom
11          def hi():\n    return 'Hi there!'\n    \n      lib_custom
12  def get_weeklyreport(name = 'all'):\n    try:\...       lib_tempo
13  import PySimpleGUI as sg\nimport pandas as pd\...       lib_tempo
14  def push_note():\n    import os\n    from pydr...       lib_tempo
15  import PySimpleGUI as sg\nimport os, sys\nimpo...         lib_sys
16  def get_folderpath():\n    try:\n        path ...         lib_sys
17  def list_function():\n    all_functions = []\n...         lib_sys
18  def push_function():\n    log = ''\n    list_f...         lib_sys
19  def get_function(libname = None):\n    log = '...         lib_sys
20  def push_sysfile(method = None):\n    log = ''...         lib_sys
21  def get_recruitment_longhai(status='all'):\n  ...      lib_custom
22  def push_recruitment_hr2():\n    import pandas...      lib_custom
23  def get_recruitment_hr2(status='all'):\n    im...      lib_custom
24  def get_sysfile():\n    log = ''\n    df = pd....         lib_sys
25  def whatis(module):\n    return pydoc.render_d...         lib_sys
26  def check_version():\n    log = ''\n    df = p...         lib_sys
27  def backup(list_files):\n    backup_folder = '...         lib_sys
28  def rollback(backup_folder):\n    list_path = ...         lib_sys
29  import random, sys, time\nfrom selenium import...         lib_bot
30  def custom_subject(subject, name):\n    return...         lib_bot
31  def custom_message(message, name):\n    return...         lib_bot
32  def send_facebook(browser, facebook, facebook_...         lib_bot
33  def run_facebook_message(min_delay = 3):\n    ...         lib_bot
34  def send_linkedin(browser, linkedin, message, ...         lib_bot
35  def run_linkedin_message(min_delay = 3):\n    ...         lib_bot
36  def send_hubspot(browser, email, subject, mess...         lib_bot
37  def send_gmail(browser, email, subject, messag...         lib_bot
38  def run_gmail_message(min_delay = 3):\n    log...         lib_bot
39  def push_product_expansion():\n    import pand...      lib_custom
40  def get_product_expansion(status='all'):\n    ...      lib_custom

               name       date_modified
0   TRAN TRUNG MINH 2020-07-06 21:03:50
1   TRAN TRUNG MINH 2020-07-06 21:03:50
2   TRAN TRUNG MINH 2020-07-06 21:03:50
3   TRAN TRUNG MINH 2020-07-06 21:03:50
4   TRAN TRUNG MINH 2020-07-06 21:03:50
5   TRAN TRUNG MINH 2020-07-06 21:03:53
6   TRAN TRUNG MINH 2020-07-06 21:03:47
7   TRAN TRUNG MINH 2020-07-06 21:03:47
8   TRAN TRUNG MINH 2020-07-06 21:03:47
9   TRAN TRUNG MINH 2020-07-06 21:03:50
10  TRAN TRUNG MINH 2020-07-06 21:03:50
11  TRAN TRUNG MINH 2020-07-06 21:03:50
12  TRAN TRUNG MINH 2020-07-06 21:03:44
13  TRAN TRUNG MINH 2020-07-06 21:03:44
14  TRAN TRUNG MINH 2020-07-06 21:03:44
15  TRAN TRUNG MINH 2020-07-06 21:03:45
16  TRAN TRUNG MINH 2020-07-06 21:03:45
17  TRAN TRUNG MINH 2020-07-06 21:03:45
18  TRAN TRUNG MINH 2020-07-06 21:03:45
19  TRAN TRUNG MINH 2020-07-06 21:03:45
20  TRAN TRUNG MINH 2020-07-06 21:03:45
21  TRAN TRUNG MINH 2020-07-06 21:03:50
22  TRAN TRUNG MINH 2020-07-06 21:03:50
23  TRAN TRUNG MINH 2020-07-06 21:03:50
24  TRAN TRUNG MINH 2020-07-06 21:03:45
25  TRAN TRUNG MINH 2020-07-06 21:03:45
26  TRAN TRUNG MINH 2020-07-06 21:03:45
27  TRAN TRUNG MINH 2020-07-06 21:03:45
28  TRAN TRUNG MINH 2020-07-06 21:03:45
29  TRAN TRUNG MINH 2020-07-06 21:03:47
30  TRAN TRUNG MINH 2020-07-06 21:03:47
31  TRAN TRUNG MINH 2020-07-06 21:03:47
32  TRAN TRUNG MINH 2020-07-06 21:03:47
33  TRAN TRUNG MINH 2020-07-06 21:03:47
34  TRAN TRUNG MINH 2020-07-06 21:03:47
35  TRAN TRUNG MINH 2020-07-06 21:03:47
36  TRAN TRUNG MINH 2020-07-06 21:03:47
37  TRAN TRUNG MINH 2020-07-06 21:03:47
38  TRAN TRUNG MINH 2020-07-06 21:03:47
39  TRAN TRUNG MINH 2020-07-06 21:03:50
40  TRAN TRUNG MINH 2020-07-06 21:03:50

In [10]:
name = 'PHUNG THANH AN'
db_functions = 'qt_functions'
df = pd.read_sql("select * from {} f_db inner join \
                 (select max(date_modified) as date_modified from {}) f_db_temp\
                 on f_db_temp.date_modified = f_db.date_modified".format(db_functions, db_functions), engine)
print(df)

         function                                            content      lib  \
0          whatis  def whatis(module):\n    return pydoc.render_d...  lib_sys
1    get_filepath  def get_filepath(filename_extension = 'all'):\...  lib_sys
2  get_folderpath  def get_folderpath():\n    try:\n        path ...  lib_sys
3   get_functions  def get_functions(libname = None):\n    log = ...  lib_sys
4  list_functions  def list_functions():\n    all_functions = []\...  lib_sys
5  push_functions  def push_functions():\n    log = ''\n    list_...  lib_sys
6    push_sysfile  def push_sysfile(sysfile = None):\n    log = '...  lib_sys
7     get_sysfile  def get_sysfile():\n    log = ''\n    df = pd....  lib_sys
8   check_version  def check_version():\n    log = ''\n    df = p...  lib_sys

             name       date_modified       date_modified
0  PHUNG THANH AN 2020-06-23 07:52:47 2020-06-23 07:52:47
1  PHUNG THANH AN 2020-06-23 07:52:47 2020-06-23 07:52:47
2  PHUNG THANH AN 2020-06-23 07:52:47 2020-06-23 07:52:47
3  PHUNG THANH AN 2020-06-23 07:52:47 2020-06-23 07:52:47
4  PHUNG THANH AN 2020-06-23 07:52:47 2020-06-23 07:52:47
5  PHUNG THANH AN 2020-06-23 07:52:47 2020-06-23 07:52:47
6  PHUNG THANH AN 2020-06-23 07:52:47 2020-06-23 07:52:47
7  PHUNG THANH AN 2020-06-23 07:52:47 2020-06-23 07:52:47
8  PHUNG THANH AN 2020-06-23 07:52:47 2020-06-23 07:52:47

In [64]:
engine.execute("SELECT * FROM TAB").fetchall()

[('BIN$p+4VSNt0SlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNthSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtiSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtjSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtkSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtlSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtmSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtnSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtoSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtpSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtqSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtrSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtsSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNttSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtuSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtvSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtwSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtxSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtySlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+4VSNtzSlLgUwIAEaxs4g==$0', 'TABLE', None),
 ('BIN$p+XNjhq1CtrgUwIAEaw3Fw==$0', 'TABLE', None),
 ('BIN$p+XNjhq2CtrgUwIAEaw3Fw==$0', 'TABLE', None),
 ('BIN$p+XNjhq3CtrgUwIAEaw3Fw==$0', 'TABLE', None),
 ('BIN$p+XNjhq4CtrgUwIAEaw3Fw==$0', 'TABLE', None),
 ('BIN$p/pAboj4LTzgUwIAEawDfw==$0', 'TABLE', None),
 ('BIN$p1Ngjyq0C4jgUwIAEayFEw==$0', 'TABLE', None),
 ('BIN$p1Ngjyq1C4jgUwIAEayFEw==$0', 'TABLE', None),
 ('BIN$p1NgjyqxC4jgUwIAEayFEw==$0', 'TABLE', None),
 ('BIN$p1NgjyqyC4jgUwIAEayFEw==$0', 'TABLE', None),
 ('BIN$p1NgjyqzC4jgUwIAEayFEw==$0', 'TABLE', None),
 ('BIN$p2Ks1rq0A1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rq1A1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rq2A1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rq3A1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rq4A1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rq5A1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rq6A1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rqvA1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rqwA1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rqxA1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rqyA1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2Ks1rqzA1/gUwIAEaycCQ==$0', 'TABLE', None),
 ('BIN$p2cqEH4ZIdrgUwIAEazYdQ==$0', 'TABLE', None),
 ('BIN$p2cqEH4aIdrgUwIAEazYdQ==$0', 'TABLE', None),
 ('BIN$p2cqEH4bIdrgUwIAEazYdQ==$0', 'TABLE', None),
 ('BIN$p52AHoZ5U0XgUwIAEawtog==$0', 'TABLE', None),
 ('BIN$p52AOY80U2TgUwIAEayoXg==$0', 'TABLE', None),
 ('BIN$p5A0HFqHbRLgUwIAEawyAw==$0', 'TABLE', None),
 ('BIN$p5A0HFqIbRLgUwIAEawyAw==$0', 'TABLE', None),
 ('BIN$p5x5cT4aTSbgUwIAEazWfw==$0', 'TABLE', None),
 ('BIN$p5x5cT4bTSbgUwIAEazWfw==$0', 'TABLE', None),
 ('BIN$p5x5cT4cTSbgUwIAEazWfw==$0', 'TABLE', None),
 ('BIN$p5x5cT4dTSbgUwIAEazWfw==$0', 'TABLE', None),
 ('BIN$p5x5cT4eTSbgUwIAEazWfw==$0', 'TABLE', None),
 ('BIN$p5x5cT4fTSbgUwIAEazWfw==$0', 'TABLE', None),
 ('BIN$p6R2u2iCDEfgUwIAEazMzw==$0', 'TABLE', None),
 ('BIN$p6R2u2iDDEfgUwIAEazMzw==$0', 'TABLE', None),
 ('BIN$p9BB7WJrSQDgUwIAEayaZQ==$0', 'TABLE', None),
 ('BIN$p9BB7WJsSQDgUwIAEayaZQ==$0', 'TABLE', None),
 ('BIN$p9BB7WJtSQDgUwIAEayaZQ==$0', 'TABLE', None),
 ('BIN$p9BB7WJuSQDgUwIAEayaZQ==$0', 'TABLE', None),
 ('BIN$p9BB7WJvSQDgUwIAEayaZQ==$0', 'TABLE', None),
 ('BIN$p9BB7WJwSQDgUwIAEayaZQ==$0', 'TABLE', None),
 ('BIN$pYgWnkS0Co3gUwIAEaxGZg==$0', 'TABLE', None),
 ('BIN$pYgWnkSzCo3gUwIAEaxGZg==$0', 'TABLE', None),
 ('BIN$pe0COpScfbjgUwIAEazY5A==$0', 'TABLE', None),
 ('BIN$pgI0RqvEJEvgUwIAEaxn7w==$0', 'TABLE', None),
 ('BIN$pgI0RqvFJEvgUwIAEaxn7w==$0', 'TABLE', None),
 ('BIN$pgKmV/nPJ47gUwIAEaxHXQ==$0', 'TABLE', None),
 ('BIN$pgKmV/nQJ47gUwIAEaxHXQ==$0', 'TABLE', None),
 ('BIN$pgKmV/nRJ47gUwIAEaxHXQ==$0', 'TABLE', None),
 ('BIN$pgKmV/nSJ47gUwIAEaxHXQ==$0', 'TABLE', None),
 ('BIN$pgKmV/nTJ47gUwIAEaxHXQ==$0', 'TABLE', None),
 ('BIN$phFzRciGG83gUwIAEaxOkQ==$0', 'TABLE', None),
 ('BIN$phj3EJskVYvgUwIAEaxoIQ==$0', 'TABLE', None),
 ('BIN$phj3EJslVYvgUwIAEaxoIQ==$0', 'TABLE', None),
 ('BIN$pt5mvw1db+fgUwIAEaxpAw==$0', 'TABLE', None),
 ('BIN$pxZHBy1iLW3gUwIAEawQiA==$0', 'TABLE', None),
 ('BIN$pxZHBy1mLW3gUwIAEawQiA==$0', 'TABLE', None),
 ('BIN$pxZHBy1oLW3gUwIAEawQiA==$0', 'TABLE', None),
 ('BIN$pxZHBy1pLW3gUwIAEawQiA==$0', 'TABLE', None),
 ('BIN$pxslmgpUUxXgUwIAEaxElA==$0', 'TABLE', None),
 ('BIN$pz/+HmBScNPgUwIAEaxI1A==$0', 'TABLE', None),
 ('BIN$pz/+HmBTcNPgUwIAEaxI1A==$0', 'TABLE', None),
 ('BIN$pz/+HmBUcNPgUwIAEaxI1A==$0', 'TABLE', None),
 ('BIN$qB+QSvqQVdfgUwIAEaw9Vw==$0', 'TABLE', None),
 ('BIN$qB/J5W/oV5ngUwIAEaz1qw==$0', 'TABLE', None),
 ('BIN$qCJcJAzra2PgUwIAEazu6A==$0', 'TABLE', None),
 ('BIN$qCLUs+Y3bxHgUwIAEawgaw==$0', 'TABLE', None),
 ('BIN$qCLUs+Y4bxHgUwIAEawgaw==$0', 'TABLE', None),
 ('BIN$qCLUs+Y5bxHgUwIAEawgaw==$0', 'TABLE', None),
 ('BIN$qCLUs+Y6bxHgUwIAEawgaw==$0', 'TABLE', None),
 ('BIN$qCLUs+Y7bxHgUwIAEawgaw==$0', 'TABLE', None),
 ('BIN$qCLUs+Y8bxHgUwIAEawgaw==$0', 'TABLE', None),
 ('BIN$qCLUs+Y9bxHgUwIAEawgaw==$0', 'TABLE', None),
 ('BIN$qCM/J/66cjfgUwIAEawQQQ==$0', 'TABLE', None),
 ('BIN$qCM/J/67cjfgUwIAEawQQQ==$0', 'TABLE', None),
 ('BIN$qDGhtZUFYsHgUwIAEaztrw==$0', 'TABLE', None),
 ('BIN$qDGhtZUGYsHgUwIAEaztrw==$0', 'TABLE', None),
 ('BIN$qDGhtZUHYsHgUwIAEaztrw==$0', 'TABLE', None),
 ('BIN$qDGhtZUIYsHgUwIAEaztrw==$0', 'TABLE', None),
 ('BIN$qDQXECRvdaPgUwIAEaylag==$0', 'TABLE', None),
 ('BIN$qDQriRp/dk/gUwIAEax2gA==$0', 'TABLE', None),
 ('BIN$qDQriRqAdk/gUwIAEax2gA==$0', 'TABLE', None),
 ('BIN$qDQriRqBdk/gUwIAEax2gA==$0', 'TABLE', None),
 ('BIN$qDQriRqCdk/gUwIAEax2gA==$0', 'TABLE', None),
 ('BIN$qDRyZCIFeGPgUwIAEawQPw==$0', 'TABLE', None),
 ('BIN$qDS36KWJeo/gUwIAEaxdZg==$0', 'TABLE', None),
 ('BIN$qDS36KWKeo/gUwIAEaxdZg==$0', 'TABLE', None),
 ('BIN$qDS36KWLeo/gUwIAEaxdZg==$0', 'TABLE', None),
 ('BIN$qDT4QBTMfIPgUwIAEax5WQ==$0', 'TABLE', None),
 ('BIN$qDT4QBTNfIPgUwIAEax5WQ==$0', 'TABLE', None),
 ('BIN$qDUHQnrDfPfgUwIAEawnKA==$0', 'TABLE', None),
 ('BIN$qDUL6BQRfRbgUwIAEazRYQ==$0', 'TABLE', None),
 ('BIN$qDUL6BQSfRbgUwIAEazRYQ==$0', 'TABLE', None),
 ('BIN$qDUL6BQTfRbgUwIAEazRYQ==$0', 'TABLE', None),
 ('BIN$qDUL6BQUfRbgUwIAEazRYQ==$0', 'TABLE', None),
 ('BIN$qDUae8/ofYXgUwIAEawlvw==$0', 'TABLE', None),
 ('BIN$qFMiR1sJaBbgUwIAEaxaKA==$0', 'TABLE', None),
 ('BIN$qHd4yrUvCBTgUwIAEayzYw==$0', 'TABLE', None),
 ('BIN$qHd4yrUxCBTgUwIAEayzYw==$0', 'TABLE', None),
 ('BIN$qK4SqmGdPgHgUwIAEaxUiA==$0', 'TABLE', None),
 ('BIN$qK4bWufRPkXgUwIAEawW4g==$0', 'TABLE', None),
 ('BIN$qK4bWufTPkXgUwIAEawW4g==$0', 'TABLE', None),
 ('BIN$qK4kfgXjPpjgUwIAEayYWw==$0', 'TABLE', None),
 ('BIN$qK4kfgXlPpjgUwIAEayYWw==$0', 'TABLE', None),
 ('BIN$qKPVL0cVbYfgUwIAEayucQ==$0', 'TABLE', None),
 ('BIN$qKPVL0cXbYfgUwIAEayucQ==$0', 'TABLE', None),
 ('BIN$qKPbf+1hbazgUwIAEazl1A==$0', 'TABLE', None),
 ('BIN$qKPbf+1jbazgUwIAEazl1A==$0', 'TABLE', None),
 ('BIN$qKQ8U/22ZuDgUwIAEayslA==$0', 'TABLE', None),
 ('BIN$qKQ8U/23ZuDgUwIAEayslA==$0', 'TABLE', None),
 ('BIN$qKStXyJUdCzgUwIAEazPUg==$0', 'TABLE', None),
 ('BIN$qKStXyJWdCzgUwIAEazPUg==$0', 'TABLE', None),
 ('BIN$qKjwEfl+FnngUwIAEawmHQ==$0', 'TABLE', None),
 ('BIN$qKjwEfmAFnngUwIAEawmHQ==$0', 'TABLE', None),
 ('BIN$qKkGsf0IFx/gUwIAEaw0Iw==$0', 'TABLE', None),
 ('BIN$qKkGsf0KFx/gUwIAEaw0Iw==$0', 'TABLE', None),
 ('BIN$qKn1rd2FHlXgUwIAEawPkQ==$0', 'TABLE', None),
 ('BIN$qL0+PRniNkfgUwIAEawzaw==$0', 'TABLE', None),
 ('BIN$qL0LRaTkNKvgUwIAEazFIw==$0', 'TABLE', None),
 ('BIN$qL0LRaTmNKvgUwIAEazFIw==$0', 'TABLE', None),
 ('BIN$qL0OSdYvNK/gUwIAEazEBw==$0', 'TABLE', None),
 ('BIN$qL0OSdYxNK/gUwIAEazEBw==$0', 'TABLE', None),
 ('BIN$qL0WKXfpNQTgUwIAEay6lg==$0', 'TABLE', None),
 ('BIN$qL0WKXfrNQTgUwIAEay6lg==$0', 'TABLE', None),
 ('BIN$qL0ZUFMoNQjgUwIAEaxm1A==$0', 'TABLE', None),
 ('BIN$qL0ZUFMqNQjgUwIAEaxm1A==$0', 'TABLE', None),
 ('BIN$qL0ZUFMsNQjgUwIAEaxm1A==$0', 'TABLE', None),
 ('BIN$qL0ZUFMuNQjgUwIAEaxm1A==$0', 'TABLE', None),
 ('BIN$qL0oCfHeNXjgUwIAEayQrg==$0', 'TABLE', None),
 ('BIN$qL0oCfHgNXjgUwIAEayQrg==$0', 'TABLE', None),
 ('BIN$qL0tU9+pNbrgUwIAEaz+LA==$0', 'TABLE', None),
 ('BIN$qL0tU9+rNbrgUwIAEaz+LA==$0', 'TABLE', None),
 ('BIN$qL1JxFiNNqDgUwIAEayHdg==$0', 'TABLE', None),
 ('BIN$qL1n7KwGN4jgUwIAEawfTw==$0', 'TABLE', None),
 ('BIN$qL1n7KwIN4jgUwIAEawfTw==$0', 'TABLE', None),
 ('BIN$qL1vjZAFN8TgUwIAEazQnA==$0', 'TABLE', None),
 ('BIN$qL1vjZAHN8TgUwIAEazQnA==$0', 'TABLE', None),
 ('BIN$qL2Bkdb2OGDgUwIAEawxDw==$0', 'TABLE', None),
 ('BIN$qL2Bkdb4OGDgUwIAEawxDw==$0', 'TABLE', None),
 ('BIN$qL2Jj4IhOLPgUwIAEawzCQ==$0', 'TABLE', None),
 ('BIN$qL2Jj4IjOLPgUwIAEawzCQ==$0', 'TABLE', None),
 ('BIN$qL2YlOxLOSngUwIAEawI8w==$0', 'TABLE', None),
 ('BIN$qL2YlOxMOSngUwIAEawI8w==$0', 'TABLE', None),
 ('BIN$qL2nSiFpOZ/gUwIAEaywyA==$0', 'TABLE', None),
 ('BIN$qL2nSiFqOZ/gUwIAEaywyA==$0', 'TABLE', None),
 ('BIN$qL2rLn8LOcDgUwIAEaw8dQ==$0', 'TABLE', None),
 ('BIN$qL2rLn8MOcDgUwIAEaw8dQ==$0', 'TABLE', None),
 ('BIN$qL3Ca9zAOmrgUwIAEaxN4Q==$0', 'TABLE', None),
 ('BIN$qL3Ca9zBOmrgUwIAEaxN4Q==$0', 'TABLE', None),
 ('BIN$qL3KWAbNOsXgUwIAEawDsA==$0', 'TABLE', None),
 ('BIN$qL3KWAbOOsXgUwIAEawDsA==$0', 'TABLE', None),
 ('BIN$qLx2OAdcL/3gUwIAEaywOQ==$0', 'TABLE', None),
 ('BIN$qLx2OAdeL/3gUwIAEaywOQ==$0', 'TABLE', None),
 ('BIN$qLx5/PeTMBrgUwIAEazJLw==$0', 'TABLE', None),
 ('BIN$qLx5/PeVMBrgUwIAEazJLw==$0', 'TABLE', None),
 ('BIN$qLxdi0c5Lz7gUwIAEawU+Q==$0', 'TABLE', None),
 ('BIN$qLxdi0c7Lz7gUwIAEawU+Q==$0', 'TABLE', None),
 ('BIN$qLyKZFKuMKXgUwIAEaz7Bg==$0', 'TABLE', None),
 ('BIN$qLyKZFKwMKXgUwIAEaz7Bg==$0', 'TABLE', None),
 ('BIN$qLyoDkD+MYXgUwIAEayL4w==$0', 'TABLE', None),
 ('BIN$qLyoDkD8MYXgUwIAEayL4w==$0', 'TABLE', None),
 ('BIN$qLzOKRlHMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRlJMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRlLMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRlNMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRlPMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRlRMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRlTMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRlVMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRlXMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRlZMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRlbMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzOKRldMr3gUwIAEax29A==$0', 'TABLE', None),
 ('BIN$qLzc3i14My/gUwIAEawgww==$0', 'TABLE', None),
 ('BIN$qLzc3i16My/gUwIAEawgww==$0', 'TABLE', None),
 ('BIN$qLzlnomOM2ngUwIAEaz/KA==$0', 'TABLE', None),
 ('BIN$qLzlnomQM2ngUwIAEaz/KA==$0', 'TABLE', None),
 ('BIN$qXGxuuCGfurgUwIAEayQWg==$0', 'TABLE', None),
 ('BIN$qZZ6A8aZIcLgUwIAEaxNKw==$0', 'TABLE', None),
 ('BIN$qZZ6A8abIcLgUwIAEaxNKw==$0', 'TABLE', None),
 ('BIN$qZZ6A8adIcLgUwIAEaxNKw==$0', 'TABLE', None),
 ('BIN$qZZ6A8afIcLgUwIAEaxNKw==$0', 'TABLE', None),
 ('BIN$qZZ6A8ahIcLgUwIAEaxNKw==$0', 'TABLE', None),
 ('BIN$qZZ6A8ajIcLgUwIAEaxNKw==$0', 'TABLE', None),
 ('BIN$qZZ6A8alIcLgUwIAEaxNKw==$0', 'TABLE', None),
 ('BIN$qZZpe/9DIUbgUwIAEaxUjg==$0', 'TABLE', None),
 ('BIN$qZZuseTdIWngUwIAEayyLg==$0', 'TABLE', None),
 ('BIN$qZZuseTfIWngUwIAEayyLg==$0', 'TABLE', None),
 ('BIN$qZZuseThIWngUwIAEayyLg==$0', 'TABLE', None),
 ('BIN$qZZuseTjIWngUwIAEayyLg==$0', 'TABLE', None),
 ('BIN$qZZuseTlIWngUwIAEayyLg==$0', 'TABLE', None),
 ('BIN$qZaIHanzIjTgUwIAEaz7zA==$0', 'TABLE', None),
 ('BIN$qZaVRC4tIqbgUwIAEawpNg==$0', 'TABLE', None),
 ('BIN$qZaVRC4vIqbgUwIAEawpNg==$0', 'TABLE', None),
 ('BIN$qZahfwPDIv/gUwIAEawV4A==$0', 'TABLE', None),
 ('BIN$qZahfwPFIv/gUwIAEawV4A==$0', 'TABLE', None),
 ('BIN$qZahfwPHIv/gUwIAEawV4A==$0', 'TABLE', None),
 ('BIN$qZoZmieJPs3gUwIAEaz5Tg==$0', 'TABLE', None),
 ('BIN$qcd8eCpULB7gUwIAEawh9Q==$0', 'TABLE', None),
 ('BIN$qdUFS4iaFmvgUwIAEawosA==$0', 'TABLE', None),
 ('DB_MEMBERINFO_DEMO', 'TABLE', None),
 ('DEMO', 'TABLE', None),
 ('LINKEDIN_DB', 'TABLE', None),
 ('QT_CODE_DEMO', 'TABLE', None),
 ('QT_FUNCTIONS', 'TABLE', None),
 ('QT_FUNCTIONS_BACKUP', 'TABLE', None),
 ('QT_HRLOCKTIME', 'TABLE', None),
 ('QT_IMAGE_WORKING', 'TABLE', None),
 ('QT_LOCKTIME', 'TABLE', None),
 ('QT_MEMBERINFO', 'TABLE', None),
 ('QT_MEMBERINFO_DEMO', 'TABLE', None),
 ('QT_MEMBERINFO_TEMP', 'TABLE', None),
 ('QT_PRODUCT_EXPANSION_PLAN', 'TABLE', None),
 ('QT_RECRUITMENT_GROUP', 'TABLE', None),
 ('QT_RECRUITMENT_HR2', 'TABLE', None),
 ('QT_RECRUITMENT_LONGHAI', 'TABLE', None),
 ('QT_SCHEDULE_INTERVIEW', 'TABLE', None),
 ('QT_TEMPOMONITOR', 'TABLE', None),
 ('QT_TEMPONOTE', 'TABLE', None),
 ('QT_TRAINNING', 'TABLE', None),
 ('QT_TRAINNING_RATE', 'TABLE', None),
 ('QT_TRAINNING_RATE_NEW', 'TABLE', None),
 ('QT_TRANSPORT', 'TABLE', None),
 ('QT_WEEKLYREPORT', 'TABLE', None),
 ('QT_WORKINGTIME', 'TABLE', None),
 ('TEST_CREATE_TABLE', 'TABLE', None),
 ('TEST_CREATE_TABLE1', 'TABLE', None),
 ('USERS', 'TABLE', None)]

In [13]:
db_functions = 'qt_functions'
function_name = 'send_gmail_messages'
df = engine.execute("delete from {} where FUNCTION like '{}' and LIB like 'lib_custom'".format(db_functions, function_name))

In [20]:
# today = today.strftime('%Y-%m-%d')
# today = datetime.date(today)
today = date(2020, 6, 7)
next_monday = today + timedelta(days=-today.weekday(),weeks=1)
df_workingtime_lock = pd.DataFrame()
df_workingtime_unlock = pd.DataFrame()
print(next_monday)
for rows in df:
    dt = datetime.date(rows[0])
    df_temp = pd.DataFrame()
    df_temp['DATETIME'] = [rows['datetime']]
    df_temp['NAME'] = [rows['name']]
    df_temp['FROM1'] = [rows['from1']]
    df_temp['TO1'] = [rows['to1']]
    df_temp['FROM2'] = [rows['from2']]
    df_temp['TO2'] = [rows['to2']]
    df_temp['FROM3'] = [rows['from3']]
    df_temp['TO3'] = [rows['to3']]
    df_temp['FROM4'] = [rows['from4']]
    df_temp['TO4'] = [rows['to4']]
    df_temp['ISSUE'] = [rows['issue']]
    df_temp['REASON'] = [rows['reason']]
    df_temp['HR_NOTE'] = [rows['hr_note']]
    df_temp['REGULAR_HOUR'] = [rows['regular_hour']]
    df_temp['REWARD_PUNISHMENT'] = [rows['reward_punishment']]
    df_temp['ACTUAL_HOUR'] = [rows['actual_hour']]
    if dt <= next_monday:
        df_workingtime_lock = pd.concat([df_workingtime_lock, df_temp])
    else:
        df_workingtime_unlock = pd.concat([df_workingtime_unlock, df_temp])
print(df_workingtime_lock)
print(df_workingtime_unlock)

2020-06-08
    DATETIME             NAME FROM1   TO1 FROM2   TO2 FROM3   TO3 FROM4   TO4  \
0 2020-06-01  TRAN TRUNG MINH  None  None    13    17    20    22  None  None
0 2020-06-02  TRAN TRUNG MINH  None  None    13    17    20    22  None  None
0 2020-06-03  TRAN TRUNG MINH  None  None    13    17    20    22  None  None
0 2020-06-04  TRAN TRUNG MINH  None  None    13    17    20    22  None  None
0 2020-06-05  TRAN TRUNG MINH  None  None    13    17    20    22  None  None
0 2020-06-06  TRAN TRUNG MINH  None  None  None  None  21.5    22  None  None
0 2020-06-07  TRAN TRUNG MINH  None  None  None  None  None  None  None  None
0 2020-06-08  TRAN TRUNG MINH  None  None    13    17    20    22  None  None

  ISSUE REASON HR_NOTE  REGULAR_HOUR REWARD_PUNISHMENT  ACTUAL_HOUR
0   nan    nan     nan           6.0              None          6.0
0   nan    nan     nan           6.0              None          6.0
0   nan    nan     nan           6.0              None          6.0
0   nan    nan     nan           6.0              None          6.0
0   nan    nan     nan           6.0              None          6.0
0   nan    nan     nan           0.5              None          0.5
0   nan    nan     nan           0.0              None          0.0
0   nan    nan     nan           6.0              None          6.0
    DATETIME             NAME FROM1   TO1 FROM2   TO2 FROM3   TO3 FROM4   TO4  \
0 2020-06-09  TRAN TRUNG MINH  None  None    13    17    20    22  None  None
0 2020-06-10  TRAN TRUNG MINH  None  None    13    17    20    22  None  None
0 2020-06-11  TRAN TRUNG MINH  None  None    13    17    20    22  None  None
0 2020-06-12  TRAN TRUNG MINH  None  None    13    17    20    22  None  None
0 2020-06-13  TRAN TRUNG MINH  None  None  None  None  21.5    22  None  None
0 2020-06-14  TRAN TRUNG MINH  None  None  None  None  None  None  None  None

  ISSUE REASON HR_NOTE  REGULAR_HOUR REWARD_PUNISHMENT  ACTUAL_HOUR
0   nan    nan     nan           6.0              None          6.0
0   nan    nan     nan           6.0              None          6.0
0   nan    nan     nan           6.0              None          6.0
0   nan    nan     nan           6.0              None          6.0
0   nan    nan     nan           0.5              None          0.5
0   nan    nan     nan           0.0              None          0.0

In [11]:
import datetime, timedelta, date
today = datetime.now()
today = datetime.date(today)
next_monday = today + datetime.timedelta(days=-today.weekday(),weeks=1)
print(next_monday)

AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'

In [14]:
from datetime import datetime, timedelta, date
unlock_date = [4,5,6] # Fr,Sa,Su
today = datetime.now()
next_monday = today + timedelta(days=-today.weekday(),weeks=1)
print(today)
print(next_monday)
if today < next_monday:
    #open permission to edit working time
    print('1')
else:
    #close permission to edit working time
    print('2')

2020-06-12 11:22:36.857612
2020-06-15 11:22:36.857612
1

In [37]:
df = pd.read_sql("select * from QT_WORKINGTIME where NAME like 'TRAN TRUNG MINH'", con)
df.columns = [x.upper() for x in df.columns]
df[:]
for df in 
print(df['DATETIME'])

SyntaxError: invalid syntax (<ipython-input-37-9d588472b4d6>, line 4)

In [26]:
text_file = open('code_demo.txt',  encoding="utf8")
lines = text_file.readlines()
print(lines)
source_code = '\n'
for line in lines:
    source_code += line
source_code += '\n'
test = 'abc'
print(type(test))
print(type(source_code))
df_test = pd.DataFrame()
df_test['name'] = ['check_permission']
df_test['code_content'] = [source_code]
df_test.to_sql('qt_code_demo', engine, if_exists='replace', index = False)
text_file.close()

['from datetime import datetime, timedelta, date\n', 'today = date.today()\n', 'def check_permission():\n', '\tunlock_date = [4,5,6] # Fr,Sa,Su\n', '\tif today.weekday() in unlock_date:\n', '\t\t#open permission\n', "\t\tprint('open permission')\n", '\t\treturn True\n', '\telse:\n', '\t\t#close permission\n', "\t\tprint('close permission')\n", '\t\treturn False']
<class 'str'>
<class 'str'>

In [35]:
df = pd.read_sql("SELECT * FROM qt_code_demo", engine)
for rows in df.iterrows():
    print(rows)
print(df['code_content'])
df_temp = df['code_content'].astype(str)
print(type(df_temp))
print(df_temp)
df_temp.to_csv(r'testfile.txt', header=None, index=None)

(0, name                                             check_permission
code_content    \nfrom datetime import datetime, timedelta, da...
Name: 0, dtype: object)
0    \nfrom datetime import datetime, timedelta, da...
Name: code_content, dtype: object
<class 'pandas.core.series.Series'>
0    \nfrom datetime import datetime, timedelta, da...
Name: code_content, dtype: object

In [36]:
new_file = open("testfile.txt", "r+")
lines = new_file.readlines()

for line in lines:
    print(line)
    if line.strip(''):
        print(line)
        new_file.write(line)
new_file.close()

"

"

from datetime import datetime, timedelta, date

from datetime import datetime, timedelta, date

today = date.today()

today = date.today()

def check_permission():

def check_permission():

	unlock_date = [4,5,6] # Fr,Sa,Su

	unlock_date = [4,5,6] # Fr,Sa,Su

	if today.weekday() in unlock_date:

	if today.weekday() in unlock_date:

		#open permission

		#open permission

		print('open permission')

		print('open permission')

		return True

		return True

	else:

	else:

		#close permission

		#close permission

		print('close permission')

		print('close permission')

		return False

		return False

"

"

In [29]:
import pandas as pd
df = pd.read_fwf('code_demo.txt', encoding="utf8")
df[:]

   from datetime import datetime, timedelta,  date
0                       today = date.today()   NaN
1                    def check_permission():   NaN
2                                        NaN   NaN
3           unlock_date = [4,5,6] # Fr,Sa,Su   NaN
4         if today.weekday() in unlock_date:   NaN
5                           #open permission   NaN
6                   print('open permission')   NaN
7                                return True   NaN
8                                      else:   NaN
9                          #close permission   NaN
10                 print('close permission')   NaN
11                              return False   NaN